### ISSUE TITLE
Аккумулятор/Состояния аккумулятора 

### ISSUE THREAD

**Issue by TARAMPAS** [ingbrzy/MA-XML-14-RUSSIAN#11]
![IMG_20230301_172735](https://user-images.githubusercontent.com/89707390/222169538-7f373fab-2095-4b05-8047-b59bc7081eac.jpg)

**Comment by mclaude74** [comment]
@TARAMPAS 
Это проблема разметки и размера шрифта от китайцев. Могу сократить до "Заряжено".  

@vlad-gamb 
Ваши мысли по поводу этого?

**Comment by vlad-gamb** [comment]
@mclaude74 сложно без правки разметки..
Мне кажется, что в этой строке "сегодня" все таки ключевое слово.. а фраза "Заряжено" будет восприниматься как общее кол-во зарядок и вызывать непонимание..
Может тогда "Зар. сегодня"?
Сокращение "зар." тоже не сразу понятно, но по другому сократить и сохранить смысл строки вряд ли получится..

**Comment by vlad-gamb** [comment]
![Screenshot_2023-03-01-18-26-00-552_com miui securitycenter](https://user-images.githubusercontent.com/97773091/222188357-1f6f974f-d6bf-4a30-be82-7f33719efab9.jpg)

**Comment by mclaude74** [comment]
@vlad-gamb 
Вкладка Экономия вроде показывает данные за сутки?

**Comment by mclaude74** [comment]
@vlad-gamb 
@TARAMPAS 
По итогу зафиксирован вариант, как на последнем скрине - "Зар. сегодня", 
включая "В норме", вместо "Норма".

**Comment by TARAMPAS** [comment]
> @vlad-gamb @TARAMPAS По итогу зафиксирован вариант, как на последнем скрине - "Зар. сегодня", включая "В норме", вместо "Норма".

Круто, спасибо. Вроде ничего серьезного, но глаз режет)
