### ISSUE TITLE
Не отображается значок NFC

### ISSUE THREAD

**Issue by omsound** [ingbrzy/MA-XML-14-RUSSIAN#14]
В строке состояния не отображается значок NFC,  xiaomi.eu_multi_DITING_V14.0.23.2.27.DEV_v14-13

![Screenshot_2023-03-08-21-05-42-959_com miui home](https://user-images.githubusercontent.com/127338178/223794361-8f0f6315-1425-42b4-b872-54c558455ee6.jpg)

![Screenshot_2023-03-08-21-05-58-116_com miui home](https://user-images.githubusercontent.com/127338178/223794369-13635e2d-0179-4b67-a62e-74e75e36a00a.jpg)

**Comment by mclaude74** [comment]
@omsound 
Эта проблема не относится к переводу, лучше сообщить в теме ошибок на форуме xiaomi.eu:
https://xiaomi.eu/community/threads/info-known-issues-weekly-faq.46800/
Либо в теме еженедельной прошивки:
https://xiaomi.eu/community/threads/23-2-27-2-28-3-6.68440/

**Comment by omsound** [comment]
Спасибо большое

**Comment by mclaude74** [comment]
@omsound 
Посмотрите этот пост https://github.com/ingbrzy/MA-XML-14-RUSSIAN/issues/1#issuecomment-1464874514

**Comment by omsound** [comment]
> @omsound Посмотрите этот пост [#1 (comment)](https://github.com/ingbrzy/MA-XML-14-RUSSIAN/issues/1#issuecomment-1464874514)

Спасибо вам большое 🙏

**Comment by omsound** [comment]
Сегодня скачал последнюю еженедельную прошивку, переключатели в строке состояния появились 🙏

**Comment by SHARP74** [comment]
![Screenshot_2023-09-05-18-17-33-052_com android updater](https://github.com/ingbrzy/MA-XML-14-RUSSIAN/assets/70298461/9deb9fba-225c-4a3d-872b-3d0c144240cc)
Такая же проблема, пропал значек NFC

**Comment by mclaude74** [comment]
@SHARP74 
Эта проблема не связана с переводом. Надо обращаться к xiaomi.eu
Насколько я знаю, некоторые значки у них сделаны настраиваемыми, т.е. можно включать/отключать в Настройках.

**Comment by omsound** [comment]
> ![Screenshot_2023-09-05-18-17-33-052_com android updater](https://user-images.githubusercontent.com/70298461/265650125-9deb9fba-225c-4a3d-872b-3d0c144240cc.jpg) Такая же проблема, пропал значек NFC

Этому сообщению "Не отображается значок NFC" скоро у него будет юбилейный )
С тех пор многое изменилось (и не все в лучшую сторону), но возможность скрытия-показа значков строки состояния сделали. Этот раздел находится в настройках "Уведомления и центр управления"
