### ISSUE TITLE
Не корректный перевод одной из настроек боковой панели 

### ISSUE THREAD

**Issue by omsound** [ingbrzy/MA-XML-14-RUSSIAN#15]
В разделе Dolby Atmos на картинке написано - Улучшение. 

![IMG_20230312_041411](https://user-images.githubusercontent.com/127338178/224519121-9ddacb19-1778-435d-9988-7ad56ac10895.jpg)

В каком то смысле это улучшение, данная настройка определяет звук голоса и усиливает его. Переключателем можно выбрать интенсивность усиления голоса.

Правильно эта настройка в версии прошивки RU MIUI 13 называется - Усиление диалогов

![Screenshot_2023-03-11-23-15-51-674_com yandex browser-edit](https://user-images.githubusercontent.com/127338178/224519225-a31503df-8070-4f87-b24a-c91b2753f3d5.jpg)

**Comment by mclaude74** [comment]
@omsound
Изменю на "Усиление голоса", на мой взгляд этот вариант лучше, чем "Усиление диалогов".

**Comment by omsound** [comment]
> @omsound Изменю на "Усиление голоса", на мой взгляд этот вариант лучше, чем "Усиление диалогов".

Смотрите как вам больше отзывается. Мне и усиление диалогов понятно. Для меня в видео роликах могут быть несколько людей, а это уже диалоги. Подразумевается что будут усилены все голоса, не один голос. Я так понимаю. Кстати эта функция работает только с видео роликами, я проверял в Ютубе. При добавлении боковой панели например в Яндекс музыку и включении этой функции звук ни как не меняется

**Comment by mclaude74** [comment]
@omsound
По идее, идёт "Усиление голоса" для каждого участника диалога. Кроме того, это может быть монолог.

**Comment by omsound** [comment]
Тогда Усиление голоса
