### ISSUE TITLE
Перевод в приложении Здоровье 

### ISSUE THREAD

**Issue by omsound** [ingbrzy/MA-XML-14-RUSSIAN#16]
При добавлении источника данных некоторые карточки устройств на китайском языке:

![Screenshot_2023-03-12-23-06-47-452_com mi health](https://user-images.githubusercontent.com/127338178/224577409-92b47d09-3f5e-4414-82af-6fce266d4669.jpg)

Не знаю, возможен перевод или нет, может они откуда-то подтягиваются

И ещё при выборе гаджета появляется карточка в которой так же китайский язык:

![Screenshot_2023-03-12-23-07-14-737_com mi health](https://user-images.githubusercontent.com/127338178/224577534-65478380-2606-46b5-9685-91fa4a85d4e4.jpg)

14.0.23.3.7 DEV, Xiaomi 12T PRO, имя пакета com.mi.health

**Comment by mclaude74** [comment]
@omsound
Китайский язык либо подтягивается с сервера, либо это проблема xiaomi.eu - они обычно модифицируют приложения так, чтобы не было экранов с китайским языком.
Я перевожу только с английского.

**Comment by omsound** [comment]
Понятно
