### ISSUE TITLE
Не корректный перевод в приложении Камера 

### ISSUE THREAD

**Issue by omsound** [ingbrzy/MA-XML-14-RUSSIAN#17]
1. Функция Таймлапс названа Ускорение, у меня был Redmi note 7, там так и было написано Таймлапс

![IMG_20230313_020150](https://user-images.githubusercontent.com/127338178/224580093-576abe94-e7cd-490c-9601-2622ca72ae02.jpg)

Слово Ускорение передает не правильное понятие этой функции, к тому же если тапнуть на иконку i , то там написано правильно и так же указано как пользоваться этой функцией

![Screenshot_2023-03-13-00-24-41-798_com android camera](https://user-images.githubusercontent.com/127338178/224580185-9342bd9f-d612-4665-892b-2674b94cfc5b.jpg)

2. Функция Замедление правильно называется Слоумо, но здесь хоть слово замедление передает понятие, что это

![IMG_20230313_020446](https://user-images.githubusercontent.com/127338178/224580325-8662896f-d645-4236-ba71-9e1c92d862ba.jpg)

Если уж правильно писать то это Замедленная съёмка. Эта фраза понятна обычным пользователям. Так же я думаю про Таймлапс и Слоумо слышал практически каждый, погуглить сможет любой и почитать про эти функции камеры. 

Если бы я писал я бы написал Таймлапс и Слоумо, так как эти функции так и называются. Даже фотографы и видеографы не говорят замедление и ускорение, профи используют термины Таймлапс и Слоумо 

14.0.23.3.7 DEV, Xiaomi 12T PRO, имя пакета com.android.camera

**Comment by omsound** [comment]
![IMG_20230313_030040](https://user-images.githubusercontent.com/127338178/224585718-93e909ac-7e5c-462c-8d8d-5b4f037ff475.jpg)

**Comment by mclaude74** [comment]
@omsound
Резонные предложения.
Заменю Ускорение на Таймлапс.
Замедленная съёмка ближе к русскому, но слишком длинно. 
Слоумо короче, но смущает меньшая распространенность, кроме того, есть мнение
https://www.google.ru/amp/s/mel.fm/amp/gramotnost/gramotny-otvet/6425107-slow_motion

@vlad-gamb
Может, у Вас будут какие-либо мысли?

**Comment by vlad-gamb** [comment]
@mclaude74 
![IMG_20230313_025335](https://user-images.githubusercontent.com/97773091/224716640-fb4aa748-7ddd-4814-a2bd-70f565341308.jpg)
В глобальной версии камеры эти пункты длительное время переводят как "Таймлапс" и "Замедление".
Может тогда сделать аналогично ей, что бы пользователям было привычнее?

**Comment by mclaude74** [comment]
@omsound 

@vlad-gamb 
Спасибо за мысли и приведённые варианты из глобальной версии (хотя она не идеал в плане перевода) :)

Заменю только ошибочное "Ускорение" на "Таймлапс".
"Замедление" пока оставлю. Если для этого пункта реализована бегущая строка, 
в можно будет заменить на "Замедленная съёмка".

**Comment by vlad-gamb** [comment]
@omsound можете показать все пункты в Камере? Те, что левее от "Замедление"?

Нужно понять, не будет ли обрезаться строка "Замедленная съёмка".

**Comment by mclaude74** [comment]
@omsound 
@vlad-gamb 
На моей старой еженедельной (MIUI 13) самые длинные пункты "Фронтальная и основная" (22 символа), "Длинная выдержка" (16) видны целиком, если вынести на начальный экран. На панели они в виде бегущей строки. Это значит, что можно использовать целиком "Замедленная съёмка" (18) и проблем с отображением не должно быть. Но и от устройства ещё зависит, да.

**Comment by mclaude74** [comment]
Р.S. "Фронтальная и основная" заменю на "Многокамерная съёмка"

**Comment by omsound** [comment]
> Р.S. "Фронтальная и основная" заменю на "Многокамерная съёмка"

Для меня как для пользователя не совсем понятна эта фраза....

А фронтальная понятно, эта та что спереди
Основная тоже понята так как первые телефоны были только с камерой на задней части,. И потом производители так же используют эти слова в характеристиках

**Comment by omsound** [comment]
> @omsound Резонные предложения. Заменю Ускорение на Таймлапс. Замедленная съёмка ближе к русскому, но слишком длинно. Слоумо короче, но смущает меньшая распространенность, кроме того, есть мнение https://www.google.ru/amp/s/mel.fm/amp/gramotnost/gramotny-otvet/6425107-slow_motion
> 
> @vlad-gamb Может, у Вас будут какие-либо мысли?

Тогда лучше Таймлапс и Замедленная съёмка, это будет ближе к русскому языку и понятию функции для русских.

**Comment by omsound** [comment]
> @omsound можете показать все пункты в Камере? Те, что левее от "Замедление"?
> 
> Нужно понять, не будет ли обрезаться строка "Замедленная съёмка".

Пожалуйста:

![Screenshot_2023-03-13-17-57-13-039_com android camera](https://user-images.githubusercontent.com/127338178/224740515-e1890636-fad8-4127-8c0f-fab896a0fa51.jpg)
![Screenshot_2023-03-13-17-57-24-616_com android camera](https://user-images.githubusercontent.com/127338178/224740523-13071236-5a6d-4f76-b632-91fc9b6c08c3.jpg)
![Screenshot_2023-03-13-17-57-41-130_com android camera](https://user-images.githubusercontent.com/127338178/224740527-a120a497-3477-4b92-b388-fb1532d861f9.jpg)

**Comment by mclaude74** [comment]
> Для меня как для пользователя не совсем понятна эта фраза....
На самом деле имеется ввиду одновременная съёмка с передней и задней камеры (одно устройство), в оригинале "Multicam", правильный перевод "Многокамерная съёмка"
Есть ещё один режим - "Двойная запись", в оригинале - "Dual phone recording" (съёмка с двух устройств, связанных по BT или Wi-Fi).

**Comment by omsound** [comment]
Для таких функций конечно должно быть описание какое то ...так сразу не поймёшь что это. Больше отзывается Двойная запись, более раскрывает понятие этой функции. На счёт Мультикам если написать по русский то не понятно )) если на английском то понятно, но это не вариант

**Comment by mclaude74** [comment]
"Двойная запись" (на глобальной так переведено) используется для съёмки двумя устройствами, связанных по BT или Wi-Fi.

"Многокамерная съёмка" (на глобальной так переведено) используется для одновременной съемки с передней и задней камеры.

**Comment by mclaude74** [comment]
@omsound 
@vlad-gamb 

По итогу уточнены понятия и поправлен перевод:

Slow Motion --> Замедленная съёмка
Time-lapse --> Таймлапс
Dual camera recording --> Двойная запись
Multicam --> Многокамерная съёмка

Тикет позже закрою.

**Comment by omsound** [comment]
> "Двойная запись" (на глобальной так переведено) используется для съёмки двумя устройствами, связанных по BT или Wi-Fi.
> 
> "Многокамерная съёмка" (на глобальной так переведено) используется для одновременной съемки с передней и задней камеры.

Тогда лучше написать как в глобальной версии, там все корректно и понятно для всех

**Comment by omsound** [comment]
> @omsound @vlad-gamb
> 
> По итогу уточнены понятия и поправлен перевод:
> 
> Slow Motion --> Замедленная съёмка Time-lapse --> Таймлапс Dual camera recording --> Двойная запись Multicam --> Многокамерная съёмка
> 
> Тикет позже закрою.

🙏
