### ISSUE TITLE
Не совсем корректный перевод раздела Центра управления 

### ISSUE THREAD

**Issue by omsound** [ingbrzy/MA-XML-14-RUSSIAN#18]
В настройках есть раздел - Уведомления и центр управления, в этом разделе есть подраздел - Дополнительные карточки, функция Mi Smart Hub переведена не совсем корректно

![IMG_20230319_022049](https://user-images.githubusercontent.com/127338178/226146337-de1a2740-3147-40bb-b715-9e9cd2138017.jpg)

Данная функция позволяет передавать не только аудиопоток на другие устройства, но и к примеру видео и многое другое 

![IMG_20230319_025613](https://user-images.githubusercontent.com/127338178/226146094-0cb3265b-b920-43ae-b3f1-e754cbfd0b8b.jpg)

Я к сожалению не нашел какого то полного описания функционала в интернете

Может посмотреть как написано в английской версии прошивки и сделать так же?

**Comment by mclaude74** [comment]
![Screenshot_2023-03-19-10-45-29-534_com android settings-edit](https://user-images.githubusercontent.com/45774262/226161231-d99b6bd0-84d3-4695-a529-7efb96c187f9.jpg)

**Comment by mclaude74** [comment]
@omsound 
У меня нет этого на MIUI13, переключите на английский и посмотрите.

Я сделаю "Управление и передача медиапотоков между устройствами"

**Comment by omsound** [comment]
> ![Screenshot_2023-03-19-10-45-29-534_com android settings-edit](https://user-images.githubusercontent.com/45774262/226161231-d99b6bd0-84d3-4695-a529-7efb96c187f9.jpg)

Тогда я ничего не понимаю )) почему такой перевод?!

**Comment by omsound** [comment]
> @omsound У меня нет этого на MIUI13, переключите на английский и посмотрите.
> 
> Я сделаю "Управление и передача медиапотоков между устройствами"

Да, так будет правильнее передавать смысл этой функции
