### ISSUE TITLE
Некорректный перевод в настройках Экрана

### ISSUE THREAD

**Issue by omsound** [ingbrzy/MA-XML-14-RUSSIAN#19]
Сейчас название этого подменю написано не совсем корректно, название говорит о том что эта настройка относится к дневному и ночному режиму, но это не так

> ![Screenshot_2023-03-31-18-06-30-126_com android settings-edit](https://user-images.githubusercontent.com/127338178/229198352-13bb8597-819d-430f-b573-45a96a0f2fc0.jpg)

Если переключить на английский то название следующее:

![IMG_20230331_180948](https://user-images.githubusercontent.com/127338178/229198646-6909e926-ada7-45f8-86cb-92a72cefdc57.jpg)

Название достаточно длинное, если нет возможности его написать то можно взять из глобальной прошивки версии RU:

![IMG_20230331_210813](https://user-images.githubusercontent.com/127338178/229198892-99ce14c2-8cbb-458d-a90f-b291e1accb1b.jpg)

**Comment by mclaude74** [comment]
@omsound 
Какая версия прошивки?

Дело в том, что на MIUI13 пункт "Дополнительные параметры" появляется только когда включён темный режим.

**Comment by mclaude74** [comment]
У меня нет устройства с MIUI14. 
Похоже в MIUI14 сломали работу этого пункта. Длинный пункт выглядит хуже, конечно.

**Comment by omsound** [comment]
Ой, извиняюсь MIUI 14.0.23.3.20 DEV

**Comment by omsound** [comment]
> У меня нет устройства с MIUI14. Похоже в MIUI14 сломали работу этого пункта. Длинный пункт выглядит хуже, конечно.

Скрины мои с MIUI 14, проверил при переключении светлого или темного режима этот пункт не исчезает и не меняет название

**Comment by mclaude74** [comment]
Странно то, что пункт у вас "Темный режим по расписанию". В репозитории перевода "Расписание тёмного режима".
Я заменил везде "темный" на "тёмный", c Ё

Проверьте, если отключить расписание тёмного режима, пункт "Дополнительные параметры" в светлом режиме не отображается.

**Comment by mclaude74** [comment]
P.S. Последний скрин с глобалки, понял.

**Comment by omsound** [comment]
> Странно то, что пункт у вас "Темный режим по расписанию". В репозитории перевода "Расписание тёмного режима". Я заменил везде "темный" на "тёмный", c Ё
> 
> Проверьте, если отключить расписание тёмного режима, пункт "Дополнительные параметры" в светлом режиме не отображается.

На счёт перевода про Ё ничего не могу сказать.

Да при отключении расписания и переходе в светлый режим этот пункт исчезает, но тогда нужно сделать чтобы при включенном расписании темного режима и переключении на светлый этот пункт исчезал. 
Но если прям как правильно было бы, написать как в глобальной версии.
Сейчас этот пункт находится внизу раздела и говорит что это Дополнительные параметры без уточнения, а значит относится и к светлому и к темному (я бы не писал если бы сам не задался вопросом, параметры всех режимов или только темного)

**Comment by mclaude74** [comment]
Хорошо, заменю на "Параметры тёмного режима"

**Comment by mclaude74** [comment]
Заменил. Тикет закрываю.
