### ISSUE TITLE
Недоперевод раздела Функции жестов и кнопок

### ISSUE THREAD

**Issue by omsound** [ingbrzy/MA-XML-14-RUSSIAN#20]
Записал видео так как практически во всех разделах есть "недоперевод"

https://user-images.githubusercontent.com/127338178/230777525-8ca8296e-8687-4219-a7b6-f1488a72e069.mp4

MIUI 14.0.23.4.2 DEV

Нижний раздел переведен не корректно "Одиночное касание", это функция постукивания по задней крышке телефона, можно "Функция постукивания" например назвать как вариант, внутри раздела соответственно Двойное постукивание и Тройное постукивание

**Comment by mclaude74** [comment]
@omsound
Об этой проблеме сообщили 
https://github.com/ingbrzy/MA-XML-14-RUSSIAN/issues/1#issuecomment-1500915745

Недоперевод уже устранил.

> Нижний раздел переведен не корректно "Одиночное касание", это функция постукивания по задней крышке телефона, можно "Функция постукивания" например назвать как вариант, внутри раздела соответственно Двойное постукивание и Тройное постукивание

Внёс правки. 

"Одиночное касание", оказывается, старая проблема и точно была ещё в MIUI12.
Не все устройства имеют такую функцию. 
На моём устройстве, например, есть функция жестов костяшкой пальца.

Вообще, судя по репортам в теме, ссылку из которой привёл, в MIUI14 "сломали" некоторые элементы интерфейса, которые были в порядке на MIUI13.

За баг-репорт спасибо. Тикет закрываю.

**Comment by omsound** [comment]
Спасибо!
