### ISSUE TITLE
HyperOS

### ISSUE THREAD

**Issue by mclaude74** [ingbrzy/MA-XML-14-RUSSIAN#22]
Hi @ingbrzy,
please make a new branch for translation HyperOS to russian language.
Thanks in advance

**Comment by mclaude74** [comment]
@ingbrzy, thanks!

**Comment by DolphinPS2** [comment]
Вылетает сторонний лаунчер и нельзя установить poco launcher hyper os .29

**Comment by mclaude74** [comment]
@DolphinPS2 
К теме перевода это же не имеет никакого отношения. 
По работоспособности прошивок и программ вопрос не ко мне.
